name = "witer-edge-security"
main = "src/index.js"
compatibility_date = "2026-07-17"

routes = [
  { pattern = "witerstudio.online/*", zone_name = "witerstudio.online" },
  { pattern = "www.witerstudio.online/*", zone_name = "witerstudio.online" }
]
