name = "witer-contact"
main = "src/index.js"
compatibility_date = "2026-07-17"

routes = [
  { pattern = "contact.witerstudio.online", custom_domain = true }
]

[vars]
ALLOWED_ORIGINS = "https://witerstudio.online,https://www.witerstudio.online"
CONTACT_TO = "studiowiter@outlook.com"
CONTACT_FROM = "contact@witerstudio.online"

[[send_email]]
name = "EMAIL"
destination_address = "studiowiter@outlook.com"
