name = "witer-contact"
main = "src/index.js"
compatibility_date = "2026-07-17"

routes = [
  { pattern = "contact.witerstudio.online", custom_domain = true }
]

[vars]
ALLOWED_ORIGINS = "https://witerstudio.online,https://www.witerstudio.online"
CONTACT_TO = "studiowiter@outlook.com"
CONTACT_FROM = "contact@witerstudio.online"

[[send_email]]
name = "EMAIL"
destination_address = "studiowiter@outlook.com"

[[d1_databases]]
binding = "DB"
database_name = "witer-contact-messages"
database_id = "e1b40cbf-7605-414a-b646-40b740b544a1"

[[ratelimits]]
name = "FORM_RATE_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 5
period = 60

[[ratelimits]]
name = "LOGIN_RATE_LIMITER"
namespace_id = "1002"

[ratelimits.simple]
limit = 5
period = 60
